# Generated by Django 4.0.3 on 2022-03-10 15:02

from django.db import migrations, models
import etherium_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_hash', models.CharField(default=etherium_api.models._createHash, max_length=20, unique=True)),
                ('tx_hash', models.CharField(default=etherium_api.models._createHash, max_length=20, unique=True)),
                ('link_to_media', models.FileField(upload_to='media/', verbose_name='Link to media')),
                ('owner', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'token',
                'verbose_name_plural': 'tokens',
            },
        ),
    ]
