# Generated by Django 4.0.3 on 2022-03-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherium_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='link_to_media',
            field=models.URLField(verbose_name='Link to media'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='owner',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='tx_hash',
            field=models.CharField(max_length=20),
        ),
    ]
