# Generated by Django 4.0.3 on 2022-03-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherium_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='owner',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='tx_hash',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='unique_hash',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
